name: Restart on Main Push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  restart-on-main-push:
    name: Restart on Main Push
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          command_timeout: 10m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sh restart-svelte.sh.sh
